<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <title>IM</title>
    <link rel="stylesheet" href="/layui/css/layui.css">
    <style>
        html{background-color: #333;}
    </style>
</head>
<body>

<script src="/layui/layui.js"></script>
<script>

    layui.use('layim', function(layim){

        let socket = new WebSocket('ws://192.168.8.11:9501');

        //连接成功时触发
        socket.onopen = function(){
            socket.send(JSON.stringify({
                action: 'open',
                data: {
                    userId: <?=$userId?>
                }
            }));
        };

        //监听收到的消息
        socket.onmessage = function(res){
            let data = JSON.parse(res.data);
            let obj = {};
            if(data.type === 'group'){
                obj = {
                    username: data.userName
                    ,avatar: data.avatar
                    ,id: data.userId
                    ,type: data.type
                    ,content: data.content
                }
            } else {
                obj = {
                    username: data.userName
                    ,avatar: data.avatar
                    ,id: data.userId
                    ,type: data.type
                    ,content: data.content
                };
                layim.setChatStatus('<span style="color:#FF5722;">在线</span>');
            }

            console.log(obj);
            layim.getMessage(obj);
        };

        //基础配置
        layim.config({

            //初始化接口
            init: {
                url: '/aj/getList'
                ,data: {}
            }

            //查看群员接口
            ,members: {
                url: '/aj/getMembers'
                ,data: {}
            }

            //上传图片接口
            ,uploadImage: {
                url: '/aj/upload/image' //（返回的数据格式见下文）
                ,type: 'post' //默认post
            }

            //上传文件接口
            ,uploadFile: {
                url: '/aj/upload/file' //（返回的数据格式见下文）
                ,type: 'post' //默认post
            }

            //扩展工具栏
            ,tool: [{
                alias: 'code'
                ,title: '代码'
                ,icon: '&#xe64e;'
            }]

            //,title: 'WebIM' //自定义主面板最小化时的标题
            //,right: '100px' //主面板相对浏览器右侧距离
            //,minRight: '90px' //聊天面板最小化时相对浏览器右侧距离
            ,initSkin: '5.jpg' //1-5 设置初始背景
            //,skin: ['aaa.jpg'] //新增皮肤
            ,isfriend: true //是否开启好友
            ,isgroup: true //是否开启群组
            //,min: true //是否始终最小化主面板，默认false
            ,notice: true //是否开启桌面消息提醒，默认false
            ,voice: 'default.wav' //声音提醒，默认开启，声音文件为：default.wav

            ,msgbox: layui.cache.dir + 'css/modules/layim/html/msgbox.html' //消息盒子页面地址，若不开启，剔除该项即可
            ,find: layui.cache.dir + 'css/modules/layim/html/find.html' //发现页面地址，若不开启，剔除该项即可
            ,chatLog: layui.cache.dir + 'css/modules/layim/html/chatLog.html' //聊天记录页面地址，若不开启，剔除该项即可

        });

        //监听在线状态的切换事件
        layim.on('online', function(data){
            //console.log(data);
        });

        //监听签名修改
        layim.on('sign', function(value){
            //console.log(value);
        });

        //监听自定义工具栏点击，以添加代码为例
        layim.on('tool(code)', function(insert){
            layer.prompt({
                title: '插入代码'
                ,formType: 2
                ,shade: 0
            }, function(text, index){
                layer.close(index);
                insert('[pre class=layui-code]' + text + '[/pre]'); //将内容插入到编辑器
            });
        });

        //监听layim建立就绪
        layim.on('ready', function(res){

            //layim.msgbox(5); //模拟消息盒子有新消息，实际使用时，一般是动态获得

            //添加好友（如果检测到该socket）
            // layim.addList({
            //     type: 'group'
            //     ,avatar: "http://tva3.sinaimg.cn/crop.64.106.361.361.50/7181dbb3jw8evfbtem8edj20ci0dpq3a.jpg"
            //     ,groupname: 'Angular开发'
            //     ,id: "12333333"
            //     ,members: 0
            // });
            // layim.addList({
            //     type: 'friend'
            //     ,avatar: "http://tp2.sinaimg.cn/2386568184/180/40050524279/0"
            //     ,username: '冲田杏梨'
            //     ,groupid: 2
            //     ,id: "1233333312121212"
            //     ,remark: "本人冲田杏梨将结束AV女优的工作"
            // });
            //
            // setTimeout(function(){
            //     //接受消息（如果检测到该socket）
            //     layim.getMessage({
            //         username: "Hi"
            //         ,avatar: "http://qzapp.qlogo.cn/qzapp/100280987/56ADC83E78CEC046F8DF2C5D0DD63CDE/100"
            //         ,id: "10000111"
            //         ,type: "friend"
            //         ,content: "临时："+ new Date().getTime()
            //     });
            // }, 3000);
        });

        //监听发送消息
        layim.on('sendMessage', function(data){
            let To = data.to;
            console.log(data);

            socket.send(JSON.stringify({action: 'chat', data: data}));

            // if(To.type === 'friend'){
            //     layim.setChatStatus('<span style="color:#FF5722;">对方正在输入。。。</span>');
            // }

            //演示自动回复
            // setTimeout(function(){
            //     var obj = {};
            //     if(To.type === 'group'){
            //         obj = {
            //             username: '模拟群员'+(Math.random()*100|0)
            //             ,avatar: layui.cache.dir + 'images/face/'+ (Math.random()*72|0) + '.gif'
            //             ,id: To.id
            //             ,type: To.type
            //             ,content: autoReplay[Math.random()*9|0]
            //         }
            //     } else {
            //         obj = {
            //             username: To.name
            //             ,avatar: To.avatar
            //             ,id: To.id
            //             ,type: To.type
            //             ,content: autoReplay[Math.random()*9|0]
            //         };
            //         layim.setChatStatus('<span style="color:#FF5722;">在线</span>');
            //     }
            //     layim.getMessage(obj);
            // }, 1000);
        });

        //监听查看群员
        layim.on('members', function(data){
            //console.log(data);
        });

        //监听聊天窗口的切换
        layim.on('chatChange', function(res){
            let type = res.data.type;
            console.log(res.data.id);
            // if(type === 'friend'){
            //     //模拟标注好友状态
            //     //layim.setChatStatus('<span style="color:#FF5722;">在线</span>');
            // } else if(type === 'group'){
            //     //模拟系统消息
            //     layim.getMessage({
            //         system: true
            //         ,id: res.data.id
            //         ,type: "group"
            //         ,content: '模拟群员'+(Math.random()*100|0) + '加入群聊'
            //     });
            // }
        });
    });
</script>
</body>
</html>
