
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <title>IM</title>
    <link rel="stylesheet" href="/layui/css/layui.mobile.css">
</head>
<body>

<script src="/layui/layui.js"></script>
<script>
    layui.use('mobile', function(){
        let mobile = layui.mobile
            ,layim = mobile.layim;

        layim.config({
            //上传图片接口
            uploadImage: {
                url: '/upload/image' //（返回的数据格式见下文）
                ,type: '' //默认post
            }

            //上传文件接口
            ,uploadFile: {
                url: '/upload/file' //（返回的数据格式见下文）
                ,type: '' //默认post
            }

            ,init: {
                mine: {
                    "username": "佟丽娅" //我的昵称
                    ,"id": 123 //我的ID
                    ,"avatar": "http://tp4.sinaimg.cn/1345566427/180/5730976522/0" //我的头像
                }
            }
        });

        //创建一个会话
        layim.chat({
            id: 111111
            ,name: 'liubang'
            ,type: 'kefu' //friend、group等字符，如果是group，则创建的是群聊
            ,avatar: 'http://tp1.sinaimg.cn/1571889140/180/40030060651/1'
        });


        //监听发送消息
        layim.on('sendMessage', function(data){

        });

        //监听查看更多记录
        layim.on('chatlog', function(data){
            console.log(data);
            layer.msg('do something');
        });
    });
</script>
</body>
</html>
