<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>webim登录</title>
    <link rel="stylesheet" href="/layui/css/layui.css">
    <script src="/layui/layui.js"></script>
    <script src="/js/jquery.min.js"></script>
</head>
<body>
<div class="layui-container" style="width: 50%; margin: 50px auto;">
    <form class="layui-form" method="post">
        <div class="layui-form-item">
            <label class="layui-form-label">输入框</label>
            <div class="layui-input-block">
                <input type="text" name="email" required  lay-verify="required" placeholder="请输入邮箱" autocomplete="off" class="layui-input">
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">密码框</label>
            <div class="layui-input-block">
                <input type="password" name="passwd" required lay-verify="required" placeholder="请输入密码" autocomplete="off" class="layui-input">
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-input-block">
                <button class="layui-btn" lay-submit="" lay-filter="formLogin">立即提交</button>
                <button type="reset" class="layui-btn layui-btn-primary">重置</button>
                <a href="/reg" class="layui-btn">注册用户</a>
            </div>
        </div>
    </form>

    <script>
        layui.use(['form', 'layer'], function () {
            let form = layui.form();
            let layer = layui.layer;
            //监听提交
            form.on('submit(formLogin)', function (data) {
                let index = layer.load(1, {
                    shade: [0.1, '#fff']
                });

                $.ajax({
                    type: "POST",
                    url: "/aj/login",
                    data: data.field,
                    success: function (data) {
                        if (~~data.code === 0) {
                            layer.msg(data.msg, {icon: 6, time: 3}, function() {
                                window.location.pathname = "/";
                                return false;
                            });
                        } else {
                            layer.close(index);
                            layer.msg(data.msg, {icon: 5});
                        }
                    }
                });

                return false;
            });
        });
    </script>
</div>
</body>
</html>