<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>webim注册</title>
    <link rel="stylesheet" href="/layui/css/layui.css">
    <script src="/layui/layui.js"></script>
    <script src="/js/jquery.min.js"></script>
</head>
<body>
<div class="layui-container" style="width: 50%; margin: 50px auto;">
    <form class="layui-form" method="post">
        <div class="layui-form-item">
            <label class="layui-form-label">用户昵称</label>
            <div class="layui-input-block">
                <input type="text" name="username" required lay-verify="required" placeholder="请输入用户名"
                       autocomplete="off" class="layui-input">
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">邮 箱</label>
            <div class="layui-input-block">
                <input type="text" name="email" required lay-verify="required|email" placeholder="请输入邮箱"
                       autocomplete="off" class="layui-input">
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">密 码</label>
            <div class="layui-input-block">
                <input type="password" name="passwd" required lay-verify="required" placeholder="请输入密码"
                       autocomplete="off" class="layui-input">
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">确认密码</label>
            <div class="layui-input-block">
                <input type="password" name="rpasswd" required lay-verify="required" placeholder="请输入密码"
                       autocomplete="off" class="layui-input">
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-input-block">
                <button type="submit" class="layui-btn" lay-submit="" lay-filter="formReg">立即提交</button>
                <button type="reset" class="layui-btn layui-btn-primary">重置</button>
            </div>
        </div>
    </form>

    <script>
        layui.use(['form', 'layer'], function () {
            let form = layui.form();
            let layer = layui.layer;
            //监听提交
            form.on('submit(formReg)', function (data) {
                let index = layer.load(1, {
                    shade: [0.1, '#fff']
                });
                // layer.msg(JSON.stringify(data.field));
                if (data.field.passwd.trim() !== data.field.rpasswd.trim()) {
                    layer.close(index);
                    layer.msg("两次密码不一致", {icon: 5});
                    return false;
                } else {
                    $.ajax({
                        type: "POST",
                        url: "/aj/reg",
                        data: data.field,
                        success: function (data) {
                            if (~~data.code === 1) {
                                layer.close(index);
                                layer.msg("注册成功", {icon: 6, time: 1500}, function() {
                                    window.location.pathname = "/login";
                                    return false;
                                });
                            } else {
                                layer.close(index);
                                layer.msg(data.msg, {icon: 5});
                            }
                        }
                    });

                    return false;
                }
            });
        });
    </script>
</div>
</body>
</html>